package org.example.app;

import static org.example.app.MessageUtils.getMessage;
import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;

import org.apache.commons.text.WordUtils;
import org.example.list.LinkedList;

/*
 * This source file was generated by the Gradle 'init' task
 */

public class App {
  public static void main(String[] args) {
    LinkedList tokens;
    tokens = split(getMessage());
    String result = join(tokens);
    System.out.println(WordUtils.capitalize(result));
  }
}
