[tools]
uv = "0.6.7"

[hooks.enter]
shell = "zsh"
script = "eval \"$(uv generate-shell-completion zsh)\""

[tasks.format]
description = ""
run = "ruff check"

[tasks.lint]
description = ""
run = "ruff format"
