/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/todolist/category/': RouteRecordInfo<'/todolist/category/', '/todolist/category', Record<never, never>, Record<never, never>>,
    '/todolist/todo/': RouteRecordInfo<'/todolist/todo/', '/todolist/todo', Record<never, never>, Record<never, never>>,
    '/todolist/todo/[todo_id]': RouteRecordInfo<'/todolist/todo/[todo_id]', '/todolist/todo/:todo_id', { todo_id: ParamValue<true> }, { todo_id: ParamValue<false> }>,
    '/todolist/todo/add': RouteRecordInfo<'/todolist/todo/add', '/todolist/todo/add', Record<never, never>, Record<never, never>>,
  }
}
